/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LocalLmTagGeneratorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LMSTUDIO_BASE_URL = "http://192.168.10.105:1234";
var LMSTUDIO_MODEL = "gpt-oss-swallow-20b-rl-v0.1";
var TAG_LIST_PATH = "templates/allowed-tags.md";
var MAX_GENERATED_TAGS = 5;
var MIN_NEW_SUGGESTIONS = 2;
var MAX_NEW_SUGGESTIONS = 5;
var MAX_NOTE_CHARS_FOR_PROMPT = 8e3;
var RETRY_MAX = 3;
var RETRY_DELAY_MS = 250;
var PREFER_STRUCTURED_OUTPUT = true;
var RIBBON_ICON = "tags";
var VIEW_TYPE_TAG_GENERATOR = "local-lm-tag-generator-sidebar";
var SIDEBAR_VIEW_TITLE = "Tag Generator";
var DEFAULT_SETTINGS = {
  newTagMode: "approval",
  newSuggestionCount: 3,
  enableSecondaryReview: true,
  autoAppendToAllowedList: false
};
var LmStudioRequestError = class extends Error {
  constructor(message, status, bodyText) {
    super(message);
    this.name = "LmStudioRequestError";
    this.status = status;
    this.bodyText = bodyText;
  }
};
var TagGeneratorSidebarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TAG_GENERATOR;
  }
  getDisplayText() {
    return SIDEBAR_VIEW_TITLE;
  }
  getIcon() {
    return RIBBON_ICON;
  }
  async onOpen() {
    await this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  async render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("local-lm-tag-generator-view");
    container.createEl("h4", { text: "Tag generation" });
    container.createEl("p", {
      text: "Generate existing tags, then optionally create and review new tags."
    });
    this.renderControls(container);
    this.renderActions(container);
    this.renderResult(container);
  }
  renderControls(container) {
    const settings = this.plugin.settings;
    new import_obsidian.Setting(container).setName("New tag mode").setDesc("New tags only: none / approval / auto").addDropdown((dropdown) => {
      dropdown.addOption("none", "\u306A\u3057");
      dropdown.addOption("approval", "\u627F\u8A8D\u5F0F");
      dropdown.addOption("auto", "\u81EA\u52D5\u8FFD\u52A0");
      dropdown.setValue(settings.newTagMode);
      dropdown.onChange(async (value) => {
        await this.plugin.updateNewTagMode(value);
      });
    });
    new import_obsidian.Setting(container).setName("New suggestion count").setDesc("How many new tag candidates to ask for (2-5)").addDropdown((dropdown) => {
      for (let i = MIN_NEW_SUGGESTIONS; i <= MAX_NEW_SUGGESTIONS; i++) {
        dropdown.addOption(String(i), String(i));
      }
      dropdown.setValue(String(settings.newSuggestionCount));
      dropdown.onChange(async (value) => {
        const parsed = Number(value);
        await this.plugin.updateNewSuggestionCount(parsed);
      });
    });
    new import_obsidian.Setting(container).setName("Secondary review agent").setDesc("Check granularity/tone similarity against existing tags").addToggle((toggle) => {
      toggle.setValue(settings.enableSecondaryReview);
      toggle.onChange(async (value) => {
        await this.plugin.updateSecondaryReview(value);
      });
    });
    new import_obsidian.Setting(container).setName("Auto append new tags to allowed list").setDesc("Initial value is OFF").addToggle((toggle) => {
      toggle.setValue(settings.autoAppendToAllowedList);
      toggle.onChange(async (value) => {
        await this.plugin.updateAutoAppendAllowedList(value);
      });
    });
  }
  renderActions(container) {
    const actionRow = container.createDiv({ cls: "local-lm-actions" });
    const runButton = new import_obsidian.ButtonComponent(actionRow).setButtonText(this.plugin.isBusy ? "Running..." : "Run Tag generation").setCta();
    if (this.plugin.isBusy) {
      runButton.setDisabled(true);
    }
    runButton.onClick(async () => {
      await this.plugin.runTagGenerationWorkflow("sidebar");
      await this.render();
    });
    if (this.plugin.settings.newTagMode === "approval") {
      const applyButton = new import_obsidian.ButtonComponent(actionRow).setButtonText(
        "Apply selected new tags"
      );
      if (this.plugin.isBusy || !this.plugin.canApplySelectedSuggestions()) {
        applyButton.setDisabled(true);
      }
      applyButton.onClick(async () => {
        await this.plugin.applySelectedSuggestions();
        await this.render();
      });
    }
  }
  renderResult(container) {
    const result = this.plugin.lastRunResult;
    if (!result) {
      container.createEl("p", {
        cls: "local-lm-muted",
        text: "Run once to see selected tags and new tag suggestions."
      });
      return;
    }
    const resultWrap = container.createDiv({ cls: "local-lm-result" });
    resultWrap.createEl("hr");
    const meta = resultWrap.createDiv({ cls: "local-lm-meta" });
    meta.createEl("div", { text: `File: ${result.filePath}` });
    meta.createEl("div", {
      text: `Coverage: ${result.coverage === "sufficient" ? "\u5341\u5206" : "\u4E0D\u8DB3"}`
    });
    this.renderTagGroup(
      resultWrap,
      "Existing tags",
      result.existingTags,
      "local-lm-chip-existing"
    );
    if (result.existingAddedTags.length > 0) {
      this.renderTagGroup(
        resultWrap,
        "Added existing tags",
        result.existingAddedTags,
        "local-lm-chip-added"
      );
    }
    if (result.appliedNewTags.length > 0) {
      this.renderTagGroup(
        resultWrap,
        "Applied new tags",
        result.appliedNewTags,
        "local-lm-chip-new"
      );
    }
    if (result.reviewedSuggestions.length > 0) {
      const section = resultWrap.createDiv({ cls: "local-lm-suggestions" });
      section.createEl("h5", { text: "New tag suggestions" });
      for (const suggestion of result.reviewedSuggestions) {
        const row = section.createDiv({ cls: "local-lm-suggestion-row" });
        if (this.plugin.settings.newTagMode === "approval") {
          const checkbox = row.createEl("input", {
            type: "checkbox",
            cls: "local-lm-suggestion-checkbox"
          });
          checkbox.checked = suggestion.selected;
          checkbox.disabled = suggestion.verdict === "reject";
          checkbox.onchange = () => {
            this.plugin.setSuggestionSelected(suggestion.tag, checkbox.checked);
          };
        }
        const body = row.createDiv({ cls: "local-lm-suggestion-body" });
        const head = body.createDiv({ cls: "local-lm-suggestion-head" });
        head.createEl("code", { text: suggestion.tag });
        head.createEl("span", {
          cls: `local-lm-badge local-lm-badge-${suggestion.verdict}`,
          text: verdictLabel(suggestion.verdict)
        });
        body.createEl("div", {
          cls: "local-lm-suggestion-reason",
          text: suggestion.reason
        });
        body.createEl("div", {
          cls: "local-lm-suggestion-scores",
          text: `confidence ${Math.round(suggestion.confidence * 100)} / granularity ${suggestion.granularityScore} / tone ${suggestion.toneScore}`
        });
        body.createEl("div", {
          cls: "local-lm-suggestion-review",
          text: suggestion.reviewReason
        });
      }
    } else {
      resultWrap.createEl("p", {
        cls: "local-lm-muted",
        text: "No new tag suggestions."
      });
    }
  }
  renderTagGroup(container, title, tags, chipClass) {
    if (tags.length === 0) return;
    const group = container.createDiv({ cls: "local-lm-group" });
    group.createEl("h5", { text: title });
    const chips = group.createDiv({ cls: "local-lm-chip-row" });
    for (const tag of tags) {
      chips.createEl("span", {
        cls: `local-lm-chip ${chipClass}`,
        text: tag
      });
    }
  }
};
var LocalLmTagGeneratorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.lastRunResult = null;
    this.isBusy = false;
  }
  async onload() {
    try {
      await this.loadSettings();
      this.registerView(
        VIEW_TYPE_TAG_GENERATOR,
        (leaf) => new TagGeneratorSidebarView(leaf, this)
      );
      this.addRibbonIcon(RIBBON_ICON, "Tag generation", async () => {
        await this.runTagGenerationWorkflow("command");
      });
      this.addCommand({
        id: "generate-tags-from-local-lmstudio",
        name: "Tag generation",
        callback: async () => {
          await this.runTagGenerationWorkflow("command");
        }
      });
      this.addCommand({
        id: "generate-tags-from-local-lmstudio-japanese",
        name: "\u30BF\u30B0\u751F\u6210\u3092\u5B9F\u884C",
        callback: async () => {
          await this.runTagGenerationWorkflow("command");
        }
      });
      this.addCommand({
        id: "open-tag-generator-sidebar",
        name: "Open Tag generator sidebar",
        callback: async () => {
          await this.activateSidebarView();
        }
      });
      this.addCommand({
        id: "apply-selected-new-tags",
        name: "Apply selected new tag suggestions",
        callback: async () => {
          await this.applySelectedSuggestions();
        }
      });
      const workspace = this.app.workspace;
      if (typeof workspace.onLayoutReady === "function") {
        workspace.onLayoutReady(() => {
          void this.activateSidebarView();
        });
      }
      new import_obsidian.Notice("Local LM Tag Generator loaded");
    } catch (err) {
      console.error("[local-lm-tag-generator] onload failed", err);
      new import_obsidian.Notice(`Local LM Tag Generator failed to load: ${errorToMessage(err)}`);
    }
  }
  async onunload() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_TAG_GENERATOR).forEach((leaf) => leaf.detach());
  }
  async activateSidebarView() {
    const { workspace } = this.app;
    const existingLeaves = workspace.getLeavesOfType(VIEW_TYPE_TAG_GENERATOR);
    if (existingLeaves.length > 0) {
      if (typeof workspace.revealLeaf === "function") {
        await workspace.revealLeaf(
          existingLeaves[0]
        );
      }
      return;
    }
    if (typeof workspace.getLeftLeaf !== "function") {
      return;
    }
    const leaf = workspace.getLeftLeaf(false);
    if (!leaf) return;
    await leaf.setViewState({
      type: VIEW_TYPE_TAG_GENERATOR,
      active: false
    });
    if (typeof workspace.revealLeaf === "function") {
      await workspace.revealLeaf(
        leaf
      );
    }
  }
  async updateNewTagMode(mode) {
    this.settings.newTagMode = mode;
    await this.saveSettings();
    this.refreshSidebarViews();
  }
  async updateNewSuggestionCount(value) {
    this.settings.newSuggestionCount = clamp(
      value,
      MIN_NEW_SUGGESTIONS,
      MAX_NEW_SUGGESTIONS
    );
    await this.saveSettings();
    this.refreshSidebarViews();
  }
  async updateSecondaryReview(enabled) {
    this.settings.enableSecondaryReview = enabled;
    await this.saveSettings();
    this.refreshSidebarViews();
  }
  async updateAutoAppendAllowedList(enabled) {
    this.settings.autoAppendToAllowedList = enabled;
    await this.saveSettings();
    this.refreshSidebarViews();
  }
  canApplySelectedSuggestions() {
    if (this.settings.newTagMode !== "approval") return false;
    if (!this.lastRunResult) return false;
    return this.lastRunResult.reviewedSuggestions.some(
      (s) => s.selected && s.verdict !== "reject"
    );
  }
  setSuggestionSelected(tag, selected) {
    if (!this.lastRunResult) return;
    const key = normalizeTag(tag).toLowerCase();
    for (const suggestion of this.lastRunResult.reviewedSuggestions) {
      if (suggestion.tag.toLowerCase() === key) {
        suggestion.selected = selected && suggestion.verdict !== "reject";
      }
    }
  }
  async applySelectedSuggestions() {
    if (!this.lastRunResult) {
      new import_obsidian.Notice("No pending suggestion result.");
      return;
    }
    if (this.settings.newTagMode !== "approval") {
      new import_obsidian.Notice("New tag mode is not set to approval.");
      return;
    }
    if (this.isBusy) {
      new import_obsidian.Notice("Tag generation is running. Please wait.");
      return;
    }
    const target = this.app.vault.getAbstractFileByPath(this.lastRunResult.filePath);
    if (!(target instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice(`Target note not found: ${this.lastRunResult.filePath}`);
      return;
    }
    const selected = this.lastRunResult.reviewedSuggestions.filter((s) => s.selected && s.verdict !== "reject").sort((a, b) => scoreSuggestion(b) - scoreSuggestion(a));
    const slots = Math.max(0, MAX_GENERATED_TAGS - this.lastRunResult.existingTags.length);
    const candidateTags = selected.slice(0, slots).map((s) => s.tag);
    if (candidateTags.length === 0) {
      new import_obsidian.Notice("No selectable new tags.");
      return;
    }
    this.isBusy = true;
    this.refreshSidebarViews();
    try {
      const applied = await this.applyTagsToFrontmatter(target, candidateTags);
      if (this.settings.autoAppendToAllowedList && applied.added.length > 0) {
        await this.appendTagsToAllowedList(applied.added);
      }
      this.lastRunResult.appliedNewTags = uniqueTags([
        ...this.lastRunResult.appliedNewTags,
        ...applied.added
      ]);
      this.lastRunResult.updatedAt = Date.now();
      if (applied.added.length > 0) {
        new import_obsidian.Notice(`Applied new tags: ${applied.added.join(", ")}`);
      } else {
        new import_obsidian.Notice("No additional new tags were applied.");
      }
    } catch (err) {
      console.error("[local-lm-tag-generator]", err);
      new import_obsidian.Notice(`Failed to apply suggestions: ${errorToMessage(err)}`);
    } finally {
      this.isBusy = false;
      this.refreshSidebarViews();
    }
  }
  async runTagGenerationWorkflow(source) {
    if (this.isBusy) {
      new import_obsidian.Notice("Tag generation is already running.");
      return;
    }
    this.isBusy = true;
    this.refreshSidebarViews();
    try {
      const file = this.app.workspace.getActiveFile();
      if (!file || file.extension !== "md") {
        new import_obsidian.Notice("Open a Markdown note before running this command.");
        return;
      }
      const allowedTags = await this.loadAllowedTags();
      if (allowedTags.length === 0) {
        new import_obsidian.Notice(`No allowed tags found at: ${TAG_LIST_PATH}`);
        return;
      }
      const rawNote = await this.app.vault.read(file);
      const noteBody = stripYamlFrontmatter(rawNote);
      const noteForPrompt = trimText(noteBody, MAX_NOTE_CHARS_FOR_PROMPT);
      const plan = await this.generateTagPlan(file, noteForPrompt, allowedTags);
      const existingApplyResult = await this.applyTagsToFrontmatter(file, plan.existingTags);
      let reviewedSuggestions = [];
      if (this.settings.newTagMode !== "none" && plan.newSuggestions.length > 0) {
        if (this.settings.enableSecondaryReview) {
          reviewedSuggestions = await this.reviewNewSuggestions(
            file,
            noteForPrompt,
            allowedTags,
            plan.existingTags,
            plan.newSuggestions
          );
        } else {
          reviewedSuggestions = plan.newSuggestions.map((s) => ({
            ...s,
            granularityScore: 100,
            toneScore: 100,
            verdict: "accept",
            reviewReason: "Secondary review disabled",
            selected: false
          }));
        }
      }
      let appliedNewTags = [];
      if (this.settings.newTagMode === "auto" && reviewedSuggestions.length > 0) {
        const slots = Math.max(0, MAX_GENERATED_TAGS - plan.existingTags.length);
        const ranked = reviewedSuggestions.filter((s) => s.verdict !== "reject").sort((a, b) => scoreSuggestion(b) - scoreSuggestion(a));
        const candidateTags = ranked.slice(0, slots).map((s) => s.tag);
        if (candidateTags.length > 0) {
          const newApplyResult = await this.applyTagsToFrontmatter(file, candidateTags);
          appliedNewTags = newApplyResult.added;
          if (this.settings.autoAppendToAllowedList && appliedNewTags.length > 0) {
            await this.appendTagsToAllowedList(appliedNewTags);
          }
        }
      }
      for (const suggestion of reviewedSuggestions) {
        suggestion.selected = this.settings.newTagMode === "approval" && suggestion.verdict === "accept";
      }
      this.lastRunResult = {
        filePath: file.path,
        existingTags: plan.existingTags,
        existingAddedTags: existingApplyResult.added,
        coverage: plan.coverage,
        reviewedSuggestions,
        appliedNewTags,
        updatedAt: Date.now()
      };
      if (this.settings.newTagMode === "approval" && reviewedSuggestions.length > 0) {
        await this.activateSidebarView();
      }
      this.notifyRunResult(source, this.lastRunResult);
    } catch (err) {
      console.error("[local-lm-tag-generator]", err);
      new import_obsidian.Notice(`Tag generation failed: ${errorToMessage(err)}`);
    } finally {
      this.isBusy = false;
      this.refreshSidebarViews();
    }
  }
  notifyRunResult(source, result) {
    const pieces = [];
    if (result.existingAddedTags.length > 0) {
      pieces.push(`existing +${result.existingAddedTags.length}`);
    }
    if (result.appliedNewTags.length > 0) {
      pieces.push(`new +${result.appliedNewTags.length}`);
    }
    if (pieces.length === 0) {
      pieces.push("no tags added");
    }
    if (this.settings.newTagMode === "approval" && result.reviewedSuggestions.length > 0) {
      const reviewCount = result.reviewedSuggestions.filter(
        (s) => s.verdict !== "reject"
      ).length;
      new import_obsidian.Notice(
        `Tag generation done (${pieces.join(", ")}). ${reviewCount} new suggestions are waiting for approval in sidebar.`
      );
      return;
    }
    if (source === "command" && this.settings.newTagMode === "approval") {
      new import_obsidian.Notice(`Tag generation done (${pieces.join(", ")}). Open sidebar to review new tags.`);
      return;
    }
    new import_obsidian.Notice(`Tag generation done (${pieces.join(", ")}).`);
  }
  async loadAllowedTags() {
    const abs = this.app.vault.getAbstractFileByPath(TAG_LIST_PATH);
    if (!(abs instanceof import_obsidian.TFile)) return [];
    const raw = await this.app.vault.read(abs);
    return parseAllowedTagFile(raw);
  }
  async appendTagsToAllowedList(tags) {
    const incoming = uniqueTags(tags);
    if (incoming.length === 0) return [];
    const abs = this.app.vault.getAbstractFileByPath(TAG_LIST_PATH);
    let current = [];
    if (abs instanceof import_obsidian.TFile) {
      const raw = await this.app.vault.read(abs);
      current = parseAllowedTagFile(raw);
    }
    const merged = uniqueTags([...current, ...incoming]);
    const currentSet = new Set(current.map((t) => t.toLowerCase()));
    const added = merged.filter((t) => !currentSet.has(t.toLowerCase()));
    if (added.length === 0) return [];
    const output = renderAllowedTagFile(merged);
    if (abs instanceof import_obsidian.TFile) {
      await this.app.vault.modify(abs, output);
    } else {
      await this.ensureParentFolders(TAG_LIST_PATH);
      await this.app.vault.create(TAG_LIST_PATH, output);
    }
    return added;
  }
  async ensureParentFolders(filePath) {
    const parts = filePath.split("/");
    parts.pop();
    let current = "";
    for (const part of parts) {
      if (!part) continue;
      current = current ? `${current}/${part}` : part;
      const abs = this.app.vault.getAbstractFileByPath(current);
      if (abs) continue;
      await this.app.vault.createFolder(current);
    }
  }
  async generateTagPlan(file, noteText, allowedTags) {
    let lastReason = "unknown";
    let useStructuredOutput = PREFER_STRUCTURED_OUTPUT;
    const targetSuggestionCount = this.settings.newTagMode === "none" ? 0 : clamp(this.settings.newSuggestionCount, MIN_NEW_SUGGESTIONS, MAX_NEW_SUGGESTIONS);
    for (let attempt = 1; attempt <= RETRY_MAX; attempt++) {
      try {
        const content = await callLmStudioChat({
          messages: buildGenerationMessages({
            file,
            noteText,
            allowedTags,
            mode: this.settings.newTagMode,
            suggestionCount: targetSuggestionCount,
            maxExistingTags: MAX_GENERATED_TAGS,
            attempt
          }),
          responseFormat: useStructuredOutput ? buildGenerationResponseFormat(allowedTags) : void 0,
          temperature: 0,
          maxTokens: 500
        });
        if (!content.trim()) {
          lastReason = "empty response";
        } else {
          const parsed = extractJsonObjectStrict(content);
          if (!parsed) {
            lastReason = "JSON parse failed";
          } else {
            const checked = validateGenerationPayload(
              parsed,
              allowedTags,
              this.settings.newTagMode,
              targetSuggestionCount
            );
            if (checked.ok) return checked.value;
            lastReason = checked.reason;
          }
        }
      } catch (err) {
        lastReason = errorToMessage(err);
        if (useStructuredOutput && looksLikeStructuredOutputUnsupported(err)) {
          useStructuredOutput = false;
        }
      }
      if (attempt < RETRY_MAX) {
        await sleep(RETRY_DELAY_MS * attempt);
      }
    }
    throw new Error(`Could not generate tags (reason: ${lastReason})`);
  }
  async reviewNewSuggestions(file, noteText, allowedTags, existingTags, suggestions) {
    if (suggestions.length === 0) return [];
    let lastReason = "unknown";
    let useStructuredOutput = PREFER_STRUCTURED_OUTPUT;
    for (let attempt = 1; attempt <= RETRY_MAX; attempt++) {
      try {
        const content = await callLmStudioChat({
          messages: buildReviewMessages({
            file,
            noteText,
            allowedTags,
            existingTags,
            suggestions,
            attempt
          }),
          responseFormat: useStructuredOutput ? buildReviewResponseFormat(suggestions) : void 0,
          temperature: 0,
          maxTokens: 400
        });
        if (!content.trim()) {
          lastReason = "empty response";
        } else {
          const parsed = extractJsonObjectStrict(content);
          if (!parsed) {
            lastReason = "JSON parse failed";
          } else {
            const checked = validateReviewPayload(parsed, suggestions);
            if (checked.ok) {
              return mergeSuggestionsWithReviews(suggestions, checked.value);
            }
            lastReason = checked.reason;
          }
        }
      } catch (err) {
        lastReason = errorToMessage(err);
        if (useStructuredOutput && looksLikeStructuredOutputUnsupported(err)) {
          useStructuredOutput = false;
        }
      }
      if (attempt < RETRY_MAX) {
        await sleep(RETRY_DELAY_MS * attempt);
      }
    }
    console.warn("[local-lm-tag-generator] secondary review fallback:", lastReason);
    return suggestions.map((s) => ({
      ...s,
      granularityScore: 60,
      toneScore: 60,
      verdict: "review",
      reviewReason: `Secondary review failed: ${lastReason}`,
      selected: false
    }));
  }
  async applyTagsToFrontmatter(file, tags) {
    const normalizedIncoming = uniqueTags(tags);
    let added = [];
    let merged = [];
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const existing = normalizeTagsFromFrontmatter(fm.tags);
      merged = uniqueTags([...existing, ...normalizedIncoming]);
      const existingSet = new Set(existing.map((t) => t.toLowerCase()));
      added = merged.filter((t) => !existingSet.has(t.toLowerCase()));
      fm.tags = merged;
    });
    return { added, merged };
  }
  refreshSidebarViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TAG_GENERATOR);
    for (const leaf of leaves) {
      if (leaf.view instanceof TagGeneratorSidebarView) {
        void leaf.view.render();
      }
    }
  }
  async loadSettings() {
    const loaded = await this.loadData();
    const merged = {
      ...DEFAULT_SETTINGS,
      ...loaded != null ? loaded : {}
    };
    merged.newSuggestionCount = clamp(
      Number(merged.newSuggestionCount),
      MIN_NEW_SUGGESTIONS,
      MAX_NEW_SUGGESTIONS
    );
    if (!isNewTagMode(merged.newTagMode)) {
      merged.newTagMode = DEFAULT_SETTINGS.newTagMode;
    }
    this.settings = merged;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function buildGenerationMessages(args) {
  const {
    file,
    noteText,
    allowedTags,
    mode,
    suggestionCount,
    maxExistingTags,
    attempt
  } = args;
  const retryHint = attempt > 1 ? "Previous output was invalid. Return strictly valid JSON now." : "";
  const modeRule = mode === "none" ? "new_tag_suggestions must be an empty array always." : [
    "If existing tags are enough, set coverage='sufficient' and return new_tag_suggestions as [].",
    `If coverage is insufficient, set coverage='insufficient' and return ${MIN_NEW_SUGGESTIONS}-${MAX_NEW_SUGGESTIONS} new tag suggestions (target about ${suggestionCount}).`
  ].join("\n");
  const systemPrompt = [
    "You are a tag planner for Obsidian notes.",
    "Pick existing_tags only from the allowed list.",
    "Do not invent tags in existing_tags.",
    `existing_tags max: ${maxExistingTags}`,
    "Output JSON object only.",
    'Required shape: {"existing_tags":[],"coverage":"sufficient|insufficient","new_tag_suggestions":[{"tag":"...","reason":"...","confidence":0.0}]}.',
    "For new_tag_suggestions, keep wording style and granularity close to allowed tags.",
    "No markdown. No prose.",
    modeRule,
    retryHint
  ].filter(Boolean).join("\n");
  const userPrompt = [
    `File name: ${file.basename}`,
    "",
    "Allowed tags:",
    allowedTags.map((t) => `- ${t}`).join("\n"),
    "",
    "Note body:",
    noteText
  ].join("\n");
  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt }
  ];
}
function buildReviewMessages(args) {
  const { file, noteText, allowedTags, existingTags, suggestions, attempt } = args;
  const retryHint = attempt > 1 ? "Previous output was invalid. Return strictly valid JSON now." : "";
  const systemPrompt = [
    "You are a secondary reviewer for new tag suggestions.",
    "Evaluate each candidate tag against allowed tags.",
    "Focus on granularity and tone similarity.",
    "Use verdict rules:",
    "- accept: both granularity and tone are close",
    "- review: borderline but potentially useful",
    "- reject: too far in granularity or tone",
    'Output JSON object only with this shape: {"reviews":[{"tag":"...","granularity_score":0-100,"tone_score":0-100,"verdict":"accept|review|reject","reason":"..."}]}.',
    "Return one review entry per candidate tag.",
    "No markdown. No prose.",
    retryHint
  ].filter(Boolean).join("\n");
  const userPrompt = [
    `File name: ${file.basename}`,
    "",
    "Allowed tags:",
    allowedTags.map((t) => `- ${t}`).join("\n"),
    "",
    "Selected existing tags:",
    existingTags.map((t) => `- ${t}`).join("\n"),
    "",
    "Candidate new tags:",
    suggestions.map((s) => `- ${s.tag} (confidence=${Math.round(s.confidence * 100)}, reason=${s.reason})`).join("\n"),
    "",
    "Note body:",
    noteText
  ].join("\n");
  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt }
  ];
}
function buildGenerationResponseFormat(allowedTags) {
  return {
    type: "json_schema",
    json_schema: {
      name: "tag_generation_plan",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          existing_tags: {
            type: "array",
            items: {
              type: "string",
              enum: allowedTags
            },
            minItems: 0,
            maxItems: MAX_GENERATED_TAGS
          },
          coverage: {
            type: "string",
            enum: ["sufficient", "insufficient"]
          },
          new_tag_suggestions: {
            type: "array",
            minItems: 0,
            maxItems: MAX_NEW_SUGGESTIONS,
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                tag: { type: "string" },
                reason: { type: "string" },
                confidence: {
                  type: "number",
                  minimum: 0,
                  maximum: 1
                }
              },
              required: ["tag", "reason", "confidence"]
            }
          }
        },
        required: ["existing_tags", "coverage", "new_tag_suggestions"]
      }
    }
  };
}
function buildReviewResponseFormat(suggestions) {
  const tagEnum = suggestions.map((s) => s.tag);
  return {
    type: "json_schema",
    json_schema: {
      name: "tag_review_result",
      schema: {
        type: "object",
        additionalProperties: false,
        properties: {
          reviews: {
            type: "array",
            minItems: 0,
            maxItems: tagEnum.length,
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                tag: { type: "string", enum: tagEnum },
                granularity_score: {
                  type: "number",
                  minimum: 0,
                  maximum: 100
                },
                tone_score: {
                  type: "number",
                  minimum: 0,
                  maximum: 100
                },
                verdict: {
                  type: "string",
                  enum: ["accept", "review", "reject"]
                },
                reason: { type: "string" }
              },
              required: [
                "tag",
                "granularity_score",
                "tone_score",
                "verdict",
                "reason"
              ]
            }
          }
        },
        required: ["reviews"]
      }
    }
  };
}
async function callLmStudioChat(args) {
  var _a, _b, _c, _d;
  const normalizedBase = LMSTUDIO_BASE_URL.replace(/\/$/, "");
  const baseWithV1 = /\/v1$/i.test(normalizedBase) ? normalizedBase : `${normalizedBase}/v1`;
  const url = `${baseWithV1}/chat/completions`;
  const payload = {
    model: LMSTUDIO_MODEL,
    temperature: args.temperature,
    max_tokens: args.maxTokens,
    messages: args.messages
  };
  if (args.responseFormat) {
    payload.response_format = args.responseFormat;
  }
  const res = await (0, import_obsidian.requestUrl)({
    url,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: "Bearer lm-studio"
    },
    body: JSON.stringify(payload)
  });
  if (res.status >= 400) {
    throw new LmStudioRequestError(
      `LM Studio HTTP ${res.status}`,
      res.status,
      String((_a = res.text) != null ? _a : "")
    );
  }
  let data;
  try {
    data = (_b = res.json) != null ? _b : JSON.parse(res.text);
  } catch (err) {
    throw new LmStudioRequestError(
      `Unable to parse LM Studio JSON response: ${errorToMessage(err)}`,
      res.status,
      String((_c = res.text) != null ? _c : "")
    );
  }
  if (typeof data === "object" && data !== null && "choices" in data && Array.isArray(data.choices)) {
    const firstChoice = data.choices[0];
    const content = (_d = firstChoice == null ? void 0 : firstChoice.message) == null ? void 0 : _d.content;
    if (typeof content === "string") return content;
  }
  return "";
}
function validateGenerationPayload(raw, allowedTags, mode, desiredSuggestionCount) {
  const allowedMap = buildAllowedTagMap(allowedTags);
  const existingRaw = raw.existing_tags;
  if (!Array.isArray(existingRaw)) {
    return { ok: false, reason: "existing_tags is not an array" };
  }
  const existingTags = [];
  const seenExisting = /* @__PURE__ */ new Set();
  for (const item of existingRaw) {
    if (typeof item !== "string") {
      return { ok: false, reason: "existing_tags has non-string value" };
    }
    const normalized = normalizeTag(item);
    if (!normalized) continue;
    const canonical = allowedMap.get(normalized.toLowerCase());
    if (!canonical) {
      return { ok: false, reason: `existing tag not allowed: ${item}` };
    }
    const key = canonical.toLowerCase();
    if (seenExisting.has(key)) continue;
    seenExisting.add(key);
    existingTags.push(canonical);
  }
  if (existingTags.length > MAX_GENERATED_TAGS) {
    return {
      ok: false,
      reason: `existing_tags exceeds limit (${MAX_GENERATED_TAGS})`
    };
  }
  const coverageRaw = raw.coverage;
  if (coverageRaw !== "sufficient" && coverageRaw !== "insufficient") {
    return { ok: false, reason: "coverage is invalid" };
  }
  const coverage = coverageRaw;
  const suggestionsRaw = raw.new_tag_suggestions;
  if (!Array.isArray(suggestionsRaw)) {
    return { ok: false, reason: "new_tag_suggestions is not an array" };
  }
  const existingSetLower = new Set(existingTags.map((t) => t.toLowerCase()));
  const allowedSetLower = new Set(allowedTags.map((t) => normalizeTag(t).toLowerCase()));
  const suggestions = [];
  const seenNew = /* @__PURE__ */ new Set();
  for (const item of suggestionsRaw) {
    if (!item || typeof item !== "object" || Array.isArray(item)) {
      return { ok: false, reason: "new_tag_suggestions has invalid item" };
    }
    const record = item;
    const tagRaw = record.tag;
    const reasonRaw = record.reason;
    const confidenceRaw = record.confidence;
    if (typeof tagRaw !== "string") {
      return { ok: false, reason: "new suggestion tag is not string" };
    }
    const normalizedTag = normalizeTag(tagRaw);
    if (!normalizedTag) continue;
    const tagKey = normalizedTag.toLowerCase();
    if (allowedSetLower.has(tagKey)) continue;
    if (existingSetLower.has(tagKey)) continue;
    if (seenNew.has(tagKey)) continue;
    const reason = typeof reasonRaw === "string" && reasonRaw.trim().length > 0 ? reasonRaw.trim() : "";
    const confidence = parseConfidence(confidenceRaw);
    suggestions.push({
      tag: normalizedTag,
      reason,
      confidence
    });
    seenNew.add(tagKey);
  }
  if (mode === "none") {
    return {
      ok: true,
      value: {
        existingTags,
        coverage,
        newSuggestions: []
      }
    };
  }
  if (coverage === "sufficient") {
    return {
      ok: true,
      value: {
        existingTags,
        coverage,
        newSuggestions: []
      }
    };
  }
  if (suggestions.length < MIN_NEW_SUGGESTIONS || suggestions.length > MAX_NEW_SUGGESTIONS) {
    return {
      ok: false,
      reason: `new suggestions count must be ${MIN_NEW_SUGGESTIONS}-${MAX_NEW_SUGGESTIONS} when coverage is insufficient`
    };
  }
  suggestions.sort((a, b) => b.confidence - a.confidence);
  const sliced = suggestions.slice(0, desiredSuggestionCount);
  if (sliced.length < MIN_NEW_SUGGESTIONS) {
    return {
      ok: false,
      reason: "not enough high-quality new suggestions"
    };
  }
  return {
    ok: true,
    value: {
      existingTags,
      coverage,
      newSuggestions: sliced
    }
  };
}
function validateReviewPayload(raw, suggestions) {
  const reviewsRaw = raw.reviews;
  if (!Array.isArray(reviewsRaw)) {
    return { ok: false, reason: "reviews is not an array" };
  }
  const suggestionMap = /* @__PURE__ */ new Map();
  for (const s of suggestions) {
    suggestionMap.set(s.tag.toLowerCase(), s);
  }
  const out = /* @__PURE__ */ new Map();
  for (const item of reviewsRaw) {
    if (!item || typeof item !== "object" || Array.isArray(item)) {
      continue;
    }
    const record = item;
    const tagRaw = record.tag;
    const granularityRaw = record.granularity_score;
    const toneRaw = record.tone_score;
    const verdictRaw = record.verdict;
    const reasonRaw = record.reason;
    if (typeof tagRaw !== "string") continue;
    const normalizedTag = normalizeTag(tagRaw);
    const key = normalizedTag.toLowerCase();
    if (!suggestionMap.has(key)) continue;
    const granularityScore = clampNumber(granularityRaw, 0, 100, 50);
    const toneScore = clampNumber(toneRaw, 0, 100, 50);
    const verdict = parseVerdict(verdictRaw, granularityScore, toneScore);
    const reason = typeof reasonRaw === "string" && reasonRaw.trim().length > 0 ? reasonRaw.trim() : "No reason";
    out.set(key, {
      tag: normalizedTag,
      granularityScore,
      toneScore,
      verdict,
      reason
    });
  }
  if (out.size === 0) {
    return { ok: false, reason: "review output had no usable rows" };
  }
  return { ok: true, value: Array.from(out.values()) };
}
function mergeSuggestionsWithReviews(suggestions, reviews) {
  const reviewMap = /* @__PURE__ */ new Map();
  for (const review of reviews) {
    reviewMap.set(review.tag.toLowerCase(), review);
  }
  const out = [];
  for (const suggestion of suggestions) {
    const key = suggestion.tag.toLowerCase();
    const review = reviewMap.get(key);
    if (review) {
      out.push({
        ...suggestion,
        granularityScore: review.granularityScore,
        toneScore: review.toneScore,
        verdict: review.verdict,
        reviewReason: review.reason,
        selected: false
      });
      continue;
    }
    out.push({
      ...suggestion,
      granularityScore: 60,
      toneScore: 60,
      verdict: "review",
      reviewReason: "No secondary review output for this tag",
      selected: false
    });
  }
  return out;
}
function parseAllowedTagFile(raw) {
  const lines = raw.split(/\r?\n/);
  const out = [];
  for (let line of lines) {
    line = line.trim();
    if (!line) continue;
    if (/^#{1,6}\s+/.test(line)) continue;
    line = line.replace(/^[-*+]\s+/, "");
    line = line.replace(/^\[[ xX]\]\s+/, "");
    line = line.replace(/^tags?\s*:\s*/i, "");
    if (!line) continue;
    const parts = line.split(",").map((s) => s.trim()).filter(Boolean);
    for (const part of parts) {
      const normalized = normalizeTag(part);
      if (normalized) out.push(normalized);
    }
  }
  return uniqueTags(out);
}
function renderAllowedTagFile(tags) {
  const normalized = uniqueTags(tags);
  const body = normalized.map((t) => `#${t}`).join("\n");
  return `# Allowed tags

${body}
`;
}
function normalizeTag(raw) {
  let tag = String(raw != null ? raw : "").trim();
  if (!tag) return "";
  tag = tag.replace(/^#+/, "").trim();
  tag = tag.replace(/^["'`]+|["'`]+$/g, "").trim();
  tag = tag.replace(/[\[\],]/g, "").trim();
  tag = tag.replace(/\s+/g, "-");
  tag = tag.replace(/[。、；;:]+$/g, "").trim();
  return tag;
}
function uniqueTags(tags) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const tag of tags) {
    const normalized = normalizeTag(tag);
    if (!normalized) continue;
    const key = normalized.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(normalized);
  }
  return out;
}
function normalizeTagsFromFrontmatter(value) {
  if (Array.isArray(value)) {
    return uniqueTags(
      value.map((item) => typeof item === "string" ? item : String(item)).map(normalizeTag).filter(Boolean)
    );
  }
  if (typeof value === "string") {
    const parts = value.split(",").map((s) => s.trim()).filter(Boolean);
    return uniqueTags(parts.map(normalizeTag).filter(Boolean));
  }
  return [];
}
function stripYamlFrontmatter(text) {
  const raw = String(text != null ? text : "");
  return raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "");
}
function trimText(text, maxChars) {
  if (text.length <= maxChars) return text;
  return text.slice(0, maxChars) + "\n\n[TRUNCATED]";
}
function extractJsonObjectStrict(text) {
  const raw = String(text != null ? text : "").trim();
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed;
    }
  } catch (e) {
  }
  const codeBlock = raw.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (codeBlock == null ? void 0 : codeBlock[1]) {
    try {
      const parsed = JSON.parse(codeBlock[1]);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return parsed;
      }
    } catch (e) {
    }
  }
  const objectMatch = raw.match(/\{[\s\S]*\}/);
  if (objectMatch == null ? void 0 : objectMatch[0]) {
    try {
      const parsed = JSON.parse(objectMatch[0]);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return parsed;
      }
    } catch (e) {
    }
  }
  return null;
}
function parseConfidence(raw) {
  if (typeof raw === "number" && Number.isFinite(raw)) {
    return clamp(raw, 0, 1);
  }
  if (typeof raw === "string") {
    const parsed = Number(raw);
    if (Number.isFinite(parsed)) return clamp(parsed, 0, 1);
  }
  return 0.5;
}
function parseVerdict(raw, granularityScore, toneScore) {
  if (raw === "accept" || raw === "review" || raw === "reject") {
    return raw;
  }
  if (granularityScore >= 75 && toneScore >= 75) return "accept";
  if (granularityScore < 45 || toneScore < 45) return "reject";
  return "review";
}
function scoreSuggestion(suggestion) {
  const verdictBase = suggestion.verdict === "accept" ? 200 : suggestion.verdict === "review" ? 100 : 0;
  return verdictBase + suggestion.granularityScore + suggestion.toneScore + Math.round(suggestion.confidence * 100);
}
function buildAllowedTagMap(allowedTags) {
  const out = /* @__PURE__ */ new Map();
  for (const tag of allowedTags) {
    const normalized = normalizeTag(tag);
    if (!normalized) continue;
    const key = normalized.toLowerCase();
    if (!out.has(key)) out.set(key, normalized);
  }
  return out;
}
function verdictLabel(verdict) {
  if (verdict === "accept") return "\u9069\u5408";
  if (verdict === "review") return "\u8981\u78BA\u8A8D";
  return "\u4E0D\u63A1\u7528";
}
function looksLikeStructuredOutputUnsupported(err) {
  const message = errorToMessage(err).toLowerCase();
  return message.includes("response_format") || message.includes("json_schema") || message.includes("structured") || message.includes("unsupported");
}
function errorToMessage(err) {
  var _a;
  if (err instanceof LmStudioRequestError) {
    const body = ((_a = err.bodyText) != null ? _a : "").slice(0, 400);
    return body ? `${err.message}: ${body}` : err.message;
  }
  if (err instanceof Error) return err.message;
  return String(err);
}
function isNewTagMode(value) {
  return value === "none" || value === "approval" || value === "auto";
}
function clamp(value, min, max) {
  if (!Number.isFinite(value)) return min;
  return Math.max(min, Math.min(max, value));
}
function clampNumber(raw, min, max, fallback) {
  if (typeof raw === "number" && Number.isFinite(raw)) {
    return clamp(raw, min, max);
  }
  if (typeof raw === "string") {
    const parsed = Number(raw);
    if (Number.isFinite(parsed)) return clamp(parsed, min, max);
  }
  return fallback;
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
